name: exe

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Nazwa brancha'
        required: true

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Install Resources script
        run: |
          ./Labka1.py

      - name: Build EXE
        run: |
          # Build the executable file
          pyinstaller --onefile Labka1.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: dist/Labka1.exe
